---
- hosts: dbslave
  handlers:
    - name: change slave server-id
      shell: id=`hostname -I |awk -F. '{print \$3\$4}'`;sed -ri "s#server-id(.*)= 1#server-id\1= ${id}#g" /etc/my.cnf
      when: ansible_hostname | search("slave")

    - name: restart mysqld
      shell: /usr/local/mysql/support-files/mysql.server restart

  tasks:
  - name:  config jinja2 my.cnf.slave mysql
    template:
      src: /etc/ansible/roles/mysql/templates/my.cnf.slave
      dest: /etc/my.cnf
      backup: true
    when: ansible_hostname | search("slave")
    notify: 
      - restart mysqld
      - change slave server-id

  - name: create dir /app/logs
    file: state=directory recurse=yes path=/app/logs owner=mysql group=mysql
    notify: 
      - restart mysqld
