---
- hosts:
  - db-master-oms-A
  - db-master-buyloan-A
  - db-master-user-pay-A
  - db-slave-all-A
  - db-slave01-home-promo-B
  - db-slave01-oms-B
  - db-slave01-product-B
  - db-slave01-risk-funding-B
  - db-slave01-buyloan-B
  - db-slave01-user-pay-B

  handlers:
    - name: install mysql
      shell: cd /usr/local/ && tar xf /usr/local/src/mysql-5.7.21-linux-glibc2.12-x86_64.tar.gz && ln -s /usr/local/mysql-5.7.21-linux-glibc2.12-x86_64 /usr/local/mysql && chown -R mysql.mysql /usr/local/mysql/

    - name: load profile
      shell: source /etc/profile

  tasks:
    - name: copy mysql.5.7.21.tar.gz
      copy:
        src: /application/src/mysql-5.7.21-linux-glibc2.12-x86_64.tar.gz
        dest: /usr/local/src/
      notify: install mysql

    - name: copy profile
      copy: 
        src: /etc/ansible/roles/mysql/files/profile
        dest: /etc/profile
        backup: true
      notify: load profile

    - name: yum install libaio
      yum: name=libaio state=latest

    - name: Create mysql user
      user:
        name: mysql
        shell: /sbin/nologin
        createhome: no
