- name: install plugin
  shell: /usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.1.2/elasticsearch-analysis-ik-6.1.2.zip

- name: restart elasticsearch
  service: name=elasticsearch state=restarted
